version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Csv2JsonApp"
s3_bucket = "wba-csv2json-bucket"
s3_prefix = "Csv2JsonApp"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

